### ISSUE TITLE
Develop a REST API for User Registration and Authentication working with Spring Boot and MongoDB

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#55]

**Comment by SimonHafner** [comment]
In this task, the user model and the user repository in the spring boot project has to be modified in order to make it compatible with Mongo DB. This also includes: Adjusting the UserPostDTO as well as all other DTO objects to the new user form data. Also, the code of the user controller and user service has to be revised accordingly. Finally, the application properties must be configured to be able to test the database connection localhost with MongoDB Compass.

**Comment by SimonHafner** [comment]
687d0f420b71041721334d5d637de1bc830482ca
